/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Generate a hybrid (X25519 + ML-KEM-768) keypair. */
export declare function generateKeypair(): Promise<{ publicKey: Buffer, secretKey: Buffer }>

/** Generate an ML-DSA-65 signing keypair. */
export declare function generateSigningKeypair(): Promise<{ publicKey: Buffer, secretKey: Buffer }>

/** A hybrid keypair returned to JS as `{ publicKey, secretKey }`. */
export interface KeyPair {
  publicKey: Buffer
  secretKey: Buffer
}

/** Decrypt a sealed message with the recipient secret key. Returns plaintext. */
export declare function open(ciphertext: Uint8Array, recipientSecretKey: Uint8Array): Promise<Buffer>

/** Hybrid-encrypt `data` to a recipient public key. Returns the sealed message. */
export declare function seal(data: Uint8Array, recipientPublicKey: Uint8Array): Promise<Buffer>

/** Sign a message with an ML-DSA-65 signing secret key. Returns the signature. */
export declare function sign(message: Uint8Array, secretKey: Uint8Array): Promise<Buffer>

/** Verify a signature over a message against an ML-DSA-65 public key. */
export declare function verify(message: Uint8Array, signature: Uint8Array, publicKey: Uint8Array): Promise<boolean>
